final class Return implements Exception {
  const Return(this.value);

  final Object? value;
}
